# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FrvqpfUTezpe60VgJRwgKP3A5UONNBFU
"""

from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
s = pd.read_csv("Bachelor_Degree_Majors.csv")
numeric_cols = [
    "Bachelor's Degree Holders",
    "Science and Engineering",
    "Science and Engineering Related Fields",
    "Business",
    "Education",
    "Arts, Humanities and Others"
]

# Преобразование в числа
for col in numeric_cols:
    s[col] = s[col].str.replace(',', '').astype(float)
female = s[s["Sex"] == "Female"]
fields = female[
    [
        "Science and Engineering",
        "Science and Engineering Related Fields",
        "Business",
        "Education",
        "Arts, Humanities and Others"
    ]
].sum()

# Строим круговую диаграмму
plt.figure(figsize=(8, 8))
plt.pie(fields.values,
        labels=fields.index,
        startangle=90,
        explode=[0.05]*5,
        autopct='%1.1f%%')
plt.title("Предпочтительные специальности для получения степени бакалавра среди мужчиин")
plt.show()

from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
s = pd.read_csv("Bachelor_Degree_Majors.csv")
numeric_cols = [
    "Bachelor's Degree Holders",
    "Science and Engineering",
    "Science and Engineering Related Fields",
    "Business",
    "Education",
    "Arts, Humanities and Others"
]

# Преобразование в числа
for col in numeric_cols:
    s[col] = s[col].str.replace(',', '').astype(float)
female = s[s["Sex"] == "Male"]
fields = female[
    [
        "Science and Engineering",
        "Science and Engineering Related Fields",
        "Business",
        "Education",
        "Arts, Humanities and Others"
    ]
].sum()

# Строим круговую диаграмму
plt.figure(figsize=(8, 8))
plt.pie(fields.values,
        labels=fields.index,
        startangle=90,
        explode=[0.05]*5,
        autopct='%1.1f%%')
plt.title("Предпочтительные специальности для получения степени бакалавра среди мужчиин")
plt.show()

from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
s = pd.read_csv("Bachelor_Degree_Majors.csv")
numeric_cols = [
    "Bachelor's Degree Holders",
    "Science and Engineering",
    "Science and Engineering Related Fields",
    "Business",
    "Education",
    "Arts, Humanities and Others"
]

# Преобразование в числа
for col in numeric_cols:
    s[col] = s[col].str.replace(',', '').astype(float)
female = s[s["Age Group"] == "65 and older"]
fields = female[
    [
        "Science and Engineering",
        "Science and Engineering Related Fields",
        "Business",
        "Education",
        "Arts, Humanities and Others"
    ]
].sum()

# Строим круговую диаграмму
plt.figure(figsize=(8, 8))
plt.pie(fields.values,
        labels=fields.index,
        startangle=90,
        explode=[0.05]*5,
        autopct='%1.1f%%')
plt.title("Предпочтительные специальности для получения степени бакалавра среди людей старше 65 лет")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

s = pd.read_csv("Bachelor_Degree_Majors.csv")

numeric_cols = [
    "Bachelor's Degree Holders",
    "Science and Engineering",
    "Science and Engineering Related Fields",
    "Business",
    "Education",
    "Arts, Humanities and Others"
]

for col in numeric_cols:
    s[col] = s[col].str.replace(',', '').astype(float)
plt.figure(figsize=(8,8))
sns.scatterplot(data=s,
                x="Science and Engineering",
                y="Business",
                hue="Sex")

plt.title("Science & Engineering и Business")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

s = pd.read_csv("Bachelor_Degree_Majors.csv")

numeric_cols = [
    "Bachelor's Degree Holders",
    "Science and Engineering",
    "Science and Engineering Related Fields",
    "Business",
    "Education",
    "Arts, Humanities and Others"
]

for col in numeric_cols:
    s[col] = s[col].str.replace(',', '').astype(float)
plt.figure(figsize=(8,8))
sns.scatterplot(data=s,
                x="Education",
                y="Arts, Humanities and Others",
                hue="Sex")

plt.title("Education vs Arts, Humanities and Others ")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

s = pd.read_csv("Bachelor_Degree_Majors.csv")

numeric_cols = [
    "Bachelor's Degree Holders",
    "Science and Engineering",
    "Science and Engineering Related Fields",
    "Business",
    "Education",
    "Arts, Humanities and Others"
]

for col in numeric_cols:
    s[col] = s[col].str.replace(',', '').astype(float)
plt.figure()
sns.boxplot(data=s,
            x="Sex",
            y="Science and Engineering")

plt.title("Наука и инженерия по полу")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

s = pd.read_csv("Bachelor_Degree_Majors.csv")
numeric_cols = [
    "Bachelor's Degree Holders",
    "Science and Engineering",
    "Science and Engineering Related Fields",
    "Business",
    "Education",
    "Arts, Humanities and Others"
]

for col in numeric_cols:
    s[col] = s[col].str.replace(',', '').astype(float)
df = pd.DataFrame(s)
df = df[(df != 0).all(axis=1)]
df

import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv("Bachelor_Degree_Majors.csv")

df["Science and Engineering"] = df["Science and Engineering"].str.replace(",", "").astype(int)
df["Business"] = df["Business"].str.replace(",", "").astype(int)

plt.figure(figsize=(10,5))

plt.bar(df["State"], df["Science and Engineering"], label="Science and Engineering")
plt.bar(df["State"], df["Business"], bottom=df["Science and Engineering"], label="Business")

plt.xticks(rotation=90)

plt.xlabel("State")
plt.ylabel("Number of Degree Holders")
plt.title("Диаграмма распределения бакалаврских степеней по направлениям")

plt.legend()

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
df = pd.read_csv("Bachelor_Degree_Majors.csv")
df["Bachelor's Degree Holders"] = (
    df["Bachelor's Degree Holders"]
    .str.replace(",", "")
    .astype(int)
)

# выбираем TOP-3
top3 = df.sort_values(
    "Bachelor's Degree Holders",
    ascending=False
).head(3)

# построение диаграммы
plt.figure(figsize=(8,5))

plt.bar(
    top3["State"],
    top3["Bachelor's Degree Holders"]
)

plt.xlabel("State")
plt.ylabel("Number of Degree Holders")
plt.title("Top 3 States by Bachelor's Degree Holders")

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# загрузка данных
df = pd.read_csv("Bachelor_Degree_Majors.csv")

# выбираем специальность
major = "Science and Engineering"

# чистим числовые столбцы
df[major] = df[major].str.replace(",", "").astype(int)

# создаём таблицу: возраст × штат
pivot = df.pivot_table(
    values=major,
    index="Age Group",
    columns="State",
    aggfunc="sum"
)

# строим heatmap
plt.figure(figsize=(14,6))

sns.heatmap(
    pivot,
    cmap="coolwarm"
)

plt.title("Наука и техника — Тепловая карта по возрастным группам и штату")
plt.xlabel("State")
plt.ylabel("Age Group")

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
df = pd.read_csv("Bachelor_Degree_Majors.csv")
cols = [
    "Bachelor's Degree Holders",
    "Science and Engineering",
    "Business",
    "Education"
]

for col in cols:
    df[col] = df[col].str.replace(",", "").astype(int)
plt.figure(figsize=(8,6))

corr = df[cols].corr()

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Зависимость между направлениями образования.")

plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("Bachelor_Degree_Majors.csv")
cols = [
    "Bachelor's Degree Holders",
    "Science and Engineering",
    "Business",
    "Education"
]

for col in cols:
    df[col] = df[col].str.replace(",", "").astype(int)
plt.figure(figsize=(10,6))

sns.boxplot(data=df[fields])

plt.title("Outliers Detection in Degree Fields")

plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns


df_raw = pd.read_csv('Bachelor_Degree_Majors.csv')

num_cols = [
    "Bachelor's Degree Holders",
    "Science and Engineering",
    "Science and Engineering Related Fields",
    "Business",
    "Education",
    "Arts, Humanities and Others"
]

for c in num_cols:
    df_raw[c] = df_raw[c].astype(str).str.replace(',', '').astype(int)

# Обрезаем до 500 строк
df = df_raw.head(500).copy()

print("Shape:", df.shape)
print(df.dtypes)
print(df.head())

dup_before = df.duplicated().sum()
df = df.drop_duplicates()
dup_after = df.duplicated().sum()

print(f'Дубликатов до: {dup_before}, после: {dup_after}')
print(f'Строк в датасете: {len(df)}')



for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    low  = Q1 - 1.5 * IQR
    high = Q3 + 1.5 * IQR
    n_out = ((df[col] < low) | (df[col] > high)).sum()
    print(f'{col}: {n_out} выбросов | границы [{int(low):,} ; {int(high):,}]')

# Диаграммы размаха
fig, axes = plt.subplots(2, 3, figsize=(14, 7))
axes = axes.flatten()
for i, col in enumerate(num_cols):
    axes[i].boxplot(df[col], vert=False, patch_artist=True,
                    boxprops=dict(facecolor='#AED6F1'))
    axes[i].set_title(col.replace(' and ', ' &\n'), fontsize=9)
    axes[i].xaxis.set_major_formatter(
        mticker.FuncFormatter(lambda x, _: f'{int(x):,}'))
    axes[i].set_xlabel('Значение')
plt.suptitle('Рисунок 1 – Диаграммы размаха числовых признаков (выявление выбросов)',
             fontsize=11)
plt.tight_layout()
plt.savefig('01_boxplots.png', dpi=150, bbox_inches='tight')
plt.show()



# Фильтр 1 — по одному признаку (Sex == "Total")
f1 = df[df['Sex'] == 'Total']
print(f'F1 | Sex == Total: {len(f1)} строк')

# Фильтр 2 — по двум признакам (Age Group == "25 to 39" AND Sex == "Female")
f2 = df[(df['Age Group'] == '25 to 39') & (df['Sex'] == 'Female')]
print(f'F2 | Age 25–39 & Female: {len(f2)} строк')

# Фильтр 3 — по числовому условию (Bachelor's Degree Holders > 500 000)
f3 = df[df["Bachelor's Degree Holders"] > 500_000]
print(f"F3 | BDH > 500 000: {len(f3)} строк")
print(f3[['State', 'Sex', 'Age Group', "Bachelor's Degree Holders"]].head(10))

comp = pd.DataFrame({
    'Фильтр':       ['Исходный датасет', 'F1: Sex == Total',
                     'F2: Age 25–39 & Female', 'F3: BDH > 500 000'],
    'Строк после':  [len(df), len(f1), len(f2), len(f3)],
})
print(comp.to_string(index=False))


rng = np.random.default_rng(42)

df_noisy = df.copy()
noise_edu  = rng.normal(0, df['Education'].std() * 0.02, size=len(df)).astype(int)
noise_arts = rng.normal(0, df['Arts, Humanities and Others'].std() * 0.02,
                        size=len(df)).astype(int)

df_noisy['Education'] = (df['Education'] + noise_edu).clip(lower=0)
df_noisy['Arts, Humanities and Others'] = (
    df['Arts, Humanities and Others'] + noise_arts).clip(lower=0)

for col in ['Education', 'Arts, Humanities and Others']:
    print(f'{col}:')
    print(f'  mean до={df[col].mean():.1f}  после={df_noisy[col].mean():.1f}')
    print(f'  std  до={df[col].std():.1f}  после={df_noisy[col].std():.1f}')

# График до/после шума
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
for ax, col in zip(axes, ['Education', 'Arts, Humanities and Others']):
    ax.hist(df[col] / 1e3,       bins=30, alpha=0.6, label='До шума',   color='#2E86C1')
    ax.hist(df_noisy[col] / 1e3, bins=30, alpha=0.6, label='После шума', color='#E74C3C')
    ax.set_title(col)
    ax.set_xlabel('Тыс. чел.')
    ax.set_ylabel('Частота')
    ax.legend()
plt.suptitle('Рисунок 2 – Добавление гауссовского шума (σ = 2% от std)', fontsize=11)
plt.tight_layout()
plt.savefig('02_noise.png', dpi=150, bbox_inches='tight')
plt.show()



# Анализ категориальных признаков на редкие значения
print("Sex:", df['Sex'].value_counts().to_dict())
print("Age Group:", df['Age Group'].value_counts().to_dict())

# Преобразование BDH в категорию
bins   = [0, 100_000, 300_000, 700_000, 1_500_000, np.inf]
labels = ['Очень малый', 'Малый', 'Средний', 'Крупный', 'Очень крупный']
df['BDH_Category'] = pd.cut(df["Bachelor's Degree Holders"], bins=bins, labels=labels)

print("\nBDH_Category:")
print(df['BDH_Category'].value_counts().to_string())




# Проверка единообразия кодировок
print("Уникальные значения Sex:", df['Sex'].unique())
print("Уникальные значения Age Group:", df['Age Group'].unique())


sex_map = {'Total': 'Tot', 'Male': 'M', 'Female': 'F'}
df['Sex_Code'] = df['Sex'].map(sex_map)
print("Sex_Code:", df['Sex_Code'].value_counts().to_dict())



fig, axes = plt.subplots(1, 2, figsize=(12, 4))
for ax, data, title in zip(axes, [df, f1],
                           ['Исходный (500 строк)', 'После фильтра F1: Sex == Total']):
    ax.hist(data['Science and Engineering'] / 1e3, bins=25,
            color='#1A5276', edgecolor='white')
    mu = data['Science and Engineering'].mean() / 1e3
    ax.axvline(mu, color='red', linestyle='--', label=f'μ = {mu:.0f}k')
    ax.set_title(title)
    ax.set_xlabel('Science and Engineering, тыс. чел.')
    ax.set_ylabel('Частота')
    ax.legend()
plt.suptitle('Рисунок 3 – Распределение S&E до и после фильтра F1', fontsize=11)
plt.tight_layout()
plt.savefig('03_after_filter.png', dpi=150, bbox_inches='tight')
plt.show()

print("Science & Engineering — mean до: {:,.0f}  после F1: {:,.0f}".format(
    df['Science and Engineering'].mean(),
    f1['Science and Engineering'].mean()))


grp = (df[df['Sex'] == 'Total']
       .groupby('Age Group')[num_cols[1:]]
       .mean()
       .round(0)
       .astype(int))

print("\nСредние значения по возрастным группам (Sex == Total):")
print(grp.to_string())

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

df = pd.read_csv("Bachelor_Degree_Majors.csv")

cols = [
    "Bachelor's Degree Holders",
    "Science and Engineering",
    "Science and Engineering Related Fields",
    "Business",
    "Education",
    "Arts, Humanities and Others"
]

for col in cols:
    df[col] = df[col].str.replace(",", "").astype(int)

sex_counts = df["Sex"].value_counts().reindex(["Male", "Female", "Total"])

plt.figure(figsize=(8, 6))
colors = ["#4472C4", "#ED7D31", "#A9D18E"]
bars = plt.bar(sex_counts.index, sex_counts.values, color=colors, edgecolor="white", width=0.5)
for bar, cnt in zip(bars, sex_counts.values):
    plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 2,
             str(cnt), ha="center", va="bottom", fontsize=12, fontweight="bold")
plt.title("Распределение по полу (Sex)", fontsize=14, fontweight="bold", pad=12)
plt.xlabel("Категория пола", fontsize=12)
plt.ylabel("Количество записей", fontsize=12)
plt.ylim(0, 250)

plt.grid(axis="y", alpha=0.3)
plt.tight_layout()

plt.show()

base = df[(df["Age Group"] == "25 and older") & (df["Sex"] == "Total")].copy()
base = base.sort_values("Bachelor's Degree Holders", ascending=False)

top10 = base.head(10)[["State", "Bachelor's Degree Holders"]]
other_sum = base.iloc[10:]["Bachelor's Degree Holders"].sum()
pie_labels = list(top10["State"]) + ["Остальные штаты"]
pie_values = list(top10["Bachelor's Degree Holders"]) + [other_sum]

plt.figure(figsize=(8, 6))
colors_pie = plt.cm.Set3(np.linspace(0, 1, 11))
wedges, texts, autotexts = plt.pie(
    pie_values, labels=None, autopct="%1.1f%%",
    colors=colors_pie, startangle=140, pctdistance=0.8
)
for at in autotexts:
    at.set_fontsize(8)
plt.legend(wedges, pie_labels, loc="center left", bbox_to_anchor=(1, 0.5), fontsize=8)
plt.title("Топ-10 штатов по числу держателей степени", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.show()

holders = base.set_index("State")["Bachelor's Degree Holders"]
small  = (holders < 300_000).sum()
medium = ((holders >= 300_000) & (holders < 1_500_000)).sum()
large  = (holders >= 1_500_000).sum()

plt.figure(figsize=(8, 6))
cats   = ["Малые\n(<300K)", "Средние\n(300K–1.5M)", "Крупные\n(>1.5M)"]
counts = [small, medium, large]
colors3 = ["#5B9BD5", "#70AD47", "#FF7043"]
bars3 = plt.bar(cats, counts, color=colors3, edgecolor="white", width=0.5)
for bar, cnt in zip(bars3, counts):
    plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.3,
             str(cnt), ha="center", va="bottom", fontsize=13, fontweight="bold")
plt.title("Новая категория: размер штата\nпо числу держателей степени", fontsize=14, fontweight="bold", pad=12)
plt.ylabel("Количество штатов", fontsize=12)
plt.ylim(0, 35)
plt.grid(axis="y", alpha=0.3)
plt.tight_layout()

plt.show()